---

- name: install chrony
  yum:
    name: chrony
    state: installed
  notify: 
    - config change

- name: template out chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  notify:
    - config change
    - restart chrony

- name: start & enable chrony
  service:
    name: chronyd
    state: started
    enabled: true
  notify: 
    - config change


